backend/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.map, name='map'),
    path('map2/', views.map2, name='map2'),
    path('datas/', views.datas, name='datas'),
    path('datas_detail_list/', views.datas_detail_list, name='datas_detail_list'),
    path('<int:id>/datas_detail', views.datas_detail, name='datas_detail'),
    path('datas2/', views.datas2, name='datas2'),
    path('<int:id>/datas2_detail/', views.datas2_detail, name='datas2_detail'),
    path('datas3/', views.datas3, name='datas3'),
    path('datas4/', views.datas4, name='datas4'),
    path('search/', views.search, name='search'),
    path('<str:crop>/crop/<str:sick>/sicksearch/', views.sicksearch, name='sicksearch'),
    path('searchtest/', views.searchtest, name='searchtest'),
]

backend/testpage/urls.py
from django.contrib import admin
from django.urls import path, include
from pages import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('pages/', include('pages.urls'))
]

backend/pages/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    
    {% endblock %}
</body>
</html>

backend/pages/templates/datas.html
{% extends 'base.html' %}
{% block body %}
<h1>datas.html</h1>
{% for data in datas %}
    <a href="{% url 'pages:datas2_detail' data.id %}">{{data.sick_name}}</a>
{% endfor %}
{% endblock %}

backend/pages/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h1>index</h1>
<h1>
    <a href="{% url 'pages:map' %}">지도로가자</a>
</h1>
<h1>
    <a href="{% url 'pages:datas' %}">농사로데이터전체조회</a>
</h1>
<h1>
    <a href="{% url 'pages:datas_detail_list' %}">농사로데이터디테일확인</a>
</h1>
<h1>
    <a href="{% url 'pages:datas2' %}">데이터2 조회</a>
</h1>
<h1>
    <a href="{% url 'pages:datas3' %}">전체 병해충 데이터</a>
</h1>
<h1>
    <a href="{% url 'pages:datas4' %}">농약 전체 데이터</a>
</h1>
<h1>
    <form action="pages/search/" method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" placeholder="작물이름" name='search_crop'>
        <input type="submit">
    </form>
</h1>
<h1>
    <form action="pages/고추/crop/탄저병/sicksearch/" method="GET" enctype="multipart/form-data">
        <input type="submit">
    </form>
</h1>
<h1>
    <a href="{% url 'pages:searchtest' %}">조회테스트용</a>
</h1>
{% endblock %}

backend/pages/templates/map.html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ko">
<head>
{% load static %}
<meta name="keywords" content="농촌진흥청, 병해충발생정보, OpenAip" charset="utf-8" />
<title>녹색기술 청색마을 함께하는 농촌진흥청(병해충예측정보 OpenAip Service)</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script type="text/javascript" src="http://ncpms.rda.go.kr/npmsAPI/api/openapiFore.jsp?googleMapKey=AIzaSyDJqEIUWbu1Au2AUXDSYd3RnFaJgxAorfk"></script>
<!-- <script type="text/javascript" src="./openapi_fore_ajax_map.js"></script> -->
<script type="text/javascript" src="{% static 'openapi_fore_ajax_map.js' %}"></script>
<script type="text/javascript">
        npmsJ(document).ready(function() {
		// Api Key
		setNpmsOpenApiKey( "2020bc251a4e18ca0830201bff4ebe390037" );
		
		// 서비스 코드
		setNpmsOpenApiServiceCode("SVC31");
		
		// 크로스 도메인 처리를 위한 콜백페이지, 꼭 서비스 도메인으로 수정해주세요.
		// 꼭 http 요청으로 보낼것!
        //setNpmsOpenApiProxyUrl("http://7e97851564ca.ngrok.io/map2");
        setNpmsOpenApiProxyUrl("http://k02c1021.p.ssafy.io:80/pages/map2/");
		
		// 넓이 조절 : OpenAPI 특성상 600px 이하로는 조절이 안됨
		setNpmsOpenAPIWidth(window.innerWidth);

		// 위치 지정 : setRegion( [지점명 혹은 주소], [줌 레벨] )
		// 지도의 중심이되는 지명 혹은 주소를 넣어주세요.
		// 줌 레벨을 변경하시어 보여지고 싶은만큼의 줌 레벨을 설정하세요.(예 : 도단위는 9, 시군 단위는 11)
		setRegion("전라남도 남원시 용담리", 14);
		
		// 서비스 작목
		// 작목코드 - 감귤:FT060614,감자:FC050501,고추:VC011205,논벼:FC010101,배:FT010602,사과:FT010601,파:VC041202,포도:FT040603
		// 서비스 하고 싶은 작목코드를 cropList 배열에 추가하여 주세요. 추가된 순서로 목록이 보여집니다.
		var cropList = new Array(
			'FT060614',//감귤
			'FC050501',//감자
			'VC011205',//고추
			'FC010101',//논벼
			'FT010602',//배
			'FT010601',//사과
			'VC041202',//파
			'FT040603'//포도
			);
		setCropList(cropList);
		
		// 지도 움직임 여부 설정
		setMoveMatAt( false );
		
		// 서비스요청
		actionMapInfo("defaultTag");
	});
</script>
</head>
<body>
    <div id="defaultTag"></div>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

backend/pages/templates/map2.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>

	<div id="NPMS" style="width: 12px;"> 
		<h1 style="font-size: 300%;">병해충 예측 지도</h1>
		<img src="http://ncpms.rda.go.kr/images/api/fore/icon_help_api.gif" style="width:62px; height:20px; border:0px; margin-top:2px; margin-left:5px; cursor:pointer;" onclick="javascript:openHelp();" />
		<div class="tabelRound"> 
			<table id="oMenuInsertTable" class="grid topLine" border="1" cellSpacing="0" cellPadding="0" name="menuInsertTable"> 
				<colgroup> 
					<col width="20%"/> 
					<col width="30%"/> 
					<col width="20%"/> 
					<col width="30%"/> 
				</colgroup> 
				<tbody> 
				<tr> 
					<th colspan="4" class="bgbr" style="height:15px"><div id="npms_api_map_desc" style="font-size:12px;">정보 제공 기간 내의 기간을 선택해주세요.</div></th> 
				</tr>
				<tr> 
					<th class="bgbr" style="height:15px">\uC791\uBAA9</th> 
					<td>'+kncrSelect+'</td> 
					<th class="bgbr">\uC815\uBCF4\uC81C\uACF5\uAE30\uAC04</th> 
					<td><div id="info_period_div"></div></td> 
				</tr> 
				<tr> 
					<th class="bgbr" style="height:15px">\uBCD1\uD574\uCDA9\uBA85</th> 
					<td><div id="dbyhsMdlCode_div"></div></td> 
					<th class="bgbr">\uC608\uCE21\uC2DC\uAC04</th> 
					<td> 
						<input type="text" name="NpmsForeDate" value="ㅇㄴㅁ" style="width:70px;height:20px" readonly> 
						<img id="npmsCalBtn" src="http://ncpms.rda.go.kr/images/icon/calendar2.gif" width="23" height="25" alt="\uB2EC\uB825\uC544\uC774\uCF58" align="top" style="cursor:pointer;"> 
						<span id="foreHour"></span> 
					</td>
				</tr> 
				</tbody> 
			</table> 
		</div> 
	</div> 

</body>
</html>

backend/pages/templates/nongsaro.html
{% extends 'base.html' %}
{% block body %}
<h1>nongsaro.html</h1>
{% for data in datas %}  
    <h1>
        <a href="{% url 'pages:datas_detail' data.id %}">
            {{data.sick_name}}
        </a>
    </h1>
{% endfor %}
{% endblock %}

backend/pages/templates/search.html
{% extends 'base.html' %}
{% block body %}
<h1>search.html</h1>
{% for data in a %}
    {{data}}
{% endfor %}
{% endblock %}

backend/pages/templates/test.html
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ko">
<head>
<meta name="keywords" content="농촌진흥청, 병해충발생정보, OpenAip" charset="utf-8" />
<title>녹색기술 청색마을 함께하는 농촌진흥청(병해충예측정보 OpenAip Service)</title>
<script type="text/javascript" src="http://ncpms.rda.go.kr/npmsAPI/api/openapiFore.jsp?googleMapKey=[구글API키]]"></script>
<script type="text/javascript">
    npmsJ(document).ready(function() {
        // Api Key
        setNpmsOpenApiKey( "[발급받은 OpenAPI 키]" );

        // 서비스 코드
        setNpmsOpenApiServiceCode("SVC31");

        // 크로스 도메인 처리를 위한 콜백페이지, 꼭 서비스 도메인으로 수정해주세요.
        setNpmsOpenApiProxyUrl("http://[서비스도메인]/openapiFore_ajax_callback.jsp");

        // 넓이 조절 : OpenAPI 특성상 600px 이하로는 조절이 안됨
        setNpmsOpenAPIWidth(600);

        // 위치 지정 : setRegion( [지점명 혹은 주소], [줌 레벨] )
        // 지도의 중심이되는 지명 혹은 주소를 넣어주세요.
        // 줌 레벨을 변경하시어 보여지고 싶은만큼의 줌 레벨을 설정하세요.(예 : 도단위는 9, 시군 단위는 11)
        setRegion("전라남도 남원시 용담리", 14);

        // 서비스 작목
        // 작목코드 - 감귤:FT060614,감자:FC050501,고추:VC011205,논벼:FC010101,배:FT010602,사과:FT010601,파:VC041202,포도:FT040603
        // 서비스 하고 싶은 작목코드를 cropList 배열에 추가하여 주세요. 추가된 순서로 목록이 보여집니다.
        var cropList = new Array('FC010101', 'FT010601','VC011205');
        setCropList(cropList);

        // 지도 움직임 여부 설정
        setMoveMatAt( false );

        // 서비스요청
        actionMapInfo("defaultTag");
    });
</script>
</head>
<body>
    <div id="defaultTag"></div>
</body>
</html>